### ISSUE TITLE
line delete doesn't work

### ISSUE THREAD

**Issue by solomon-negusse** [twdb/hydropick#138]
per Holly:

Bugs, bugs, bugs. When I try to delete a surface it disappears from the list and view as if it worked, but when I leave the line and then come back to it, the surface is back. Example: Bachman lines 15021927 and 15021928 trying to delete the surface called PRE_Pre50fromcurrent
 
I put the updated Bachman project here: S:\Shared\90Temp\Hydrosurvey\Hydropick2

**Comment by toddjm** [comment]
In the Hydrosurvey directory, I see multiple paths for files with the same name, for instance "SurveyData" shows up twice (as does the project):

/S/Shared/90Temp/Hydrosurvey/Hydropick2/Bachman/2015/SurveyData/Bachman_2015-project/SurveyData/Bachman_2015-project

I believe the path confusion is causing the problem. Can you please clean up that directory so that we can debug?

**Comment by toddjm** [comment]
Closed #140
